import os
from fetu_cards import *

''' KrypoMagick N Heka Fetu Cards version 'AAG' '''


hka_orderA = generate_random_deck_order()
hka_orderB = generate_random_deck_order()
hka_deckA = generate_deck(hka_orderA)
hka_deckB = generate_deck(hka_orderB)
deck_msgA = convert_deck_to_msg(hka_deckA)
deck_msgB = convert_deck_to_msg(hka_deckB)
comb_deck, comb_deck_msg = add_decks([hka_deckA, hka_deckB])
comb_deck_subtracted, comb_deck_msg_s = subtract_decks([hka_deckA, hka_deckB])
ma_valuesA, totalA, ma_totalA = get_deck_values(hka_deckA)
ma_valuesB, totalB, ma_totalB = get_deck_values(hka_deckB)
glyphsA, glyph_sums4A, glyph_total4A = get_fetu_glyphs(hka_deckA)
glyphsB, glyph_sums4B, glyph_total4B = get_fetu_glyphs(hka_deckB)
wiqa_seqFA = wiqa_sequence_forward(hka_deckA)
wiqa_seqBA = wiqa_sequence_backA(hka_deckA)
wiqa_seqBAB = wiqa_sequence_backB(hka_deckA)
print_deck(hka_deckA)
print_deck(hka_deckB)
print(deck_msgA)
print(deck_msgB)
print(comb_deck, comb_deck_msg)
print(comb_deck_subtracted, comb_deck_msg_s)
print(ma_valuesA, totalA, ma_totalA)
print(ma_valuesB, totalB, ma_totalB)
print(wiqa_seqFA, wiqa_seqBA, wiqa_seqBAB)
print(glyphsA, glyph_sums4A, glyph_total4A)
print(glyphsB, glyph_sums4B, glyph_total4B)
export_deck(hka_deckA)
export_deck(hka_deckB)

signatureAA, signatureAB = get_deck_signature(glyph_total4A, totalA)
signatureBA, signatureBB = get_deck_signature(glyph_total4B, totalB)
print(signatureAA, signatureAB)
print(signatureBA, signatureBB)

p = nearest_prime(signatureAB)
q = nearest_prime(signatureBB)
print(p, q)

''' Modulus Deck '''

hka_orderM = generate_random_deck_order()
hka_deckM = generate_deck(hka_orderM)

ma_valuesM, totalM, ma_totalM = get_deck_values(hka_deckM)
glyphsM, glyph_sums4M, glyph_total4M = get_fetu_glyphs(hka_deckM)

signatureMA, signatureMB = get_deck_signature(glyph_total4M, totalM)

s = nearest_prime(signatureBB)
print(signatureMB, s)

hexsigintA, hexsig_hexA, bin_msgA = get_fetu_binary_message(hka_deckA)
print("Fetu Hex/Binary Signatures: ")
print(hexsig_hexA, hexsigintA, bin_msgA)

max_binA, bin_totalA, max_hexA, max_decA, fetu_totalA, fetu_totalsA, ovr_decA, ovr_dec_dblA, ovr_dec_dbl_hexA, max_squeeze_decA, max_squeeze_hexA = fetu_max_entropy(hka_deckA)
max_binB, bin_totalB, max_hexB, max_decB, fetu_totalB, fetu_totalsB, ovr_decB, ovr_dec_dblB, ovr_dec_dbl_hexB, max_squeeze_decB, max_squeeze_hexB = fetu_max_entropy(hka_deckB)
print("Max Entropy Function Report --- ")
print("--- 584 bit entropy extraction --- ")
print("Hex String: ", max_hexA)
print("Decimal String: ", str(max_decA))
print("Max Entropy Binary Values: "+str(max_binA))
print("Max Entropy Binary Total: "+str(bin_totalA))
print("Fetu Total: ", str(fetu_totalA))
print("Fetu Totals: ", str(fetu_totalsA))
#print("Overdrive Decimal: ", str(ovr_decA))
#print("Overdrive Decimal Double: ", str(ovr_dec_dblA))
print("Overdrive Double Hex String: ", str(ovr_dec_dbl_hexA))
#print("Max Squeeze Decimal: ", str(max_squeeze_decB))
#print("Max Squeeze Hex String: ", str(max_squeeze_hexB))
print("\n")
print("Hex String: ", max_hexB)
print("Decimal String: ", str(max_decB))
print("Max Entropy Binary Values: "+str(max_binB))
print("Max Entropy Binary Total: "+str(bin_totalB))
print("Fetu Total: ", str(fetu_totalB))
print("Fetu Totals: ", str(fetu_totalsB))
#print("Overdrive Decimal: ", str(ovr_decB))
#print("Overdrive Decimal Double: ", str(ovr_dec_dblB))
print("Overdrive Double Hex String: ", str(ovr_dec_dbl_hexB))
#print("Max Squeeze Decimal: ", str(max_squeeze_decB))
#print("Max Squeeze Hex String: ", str(max_squeeze_hexB))
print((((len(ovr_dec_dbl_hexB) - 2) / 2) * 8))
hexsigintB, hexsig_hexB, bin_msgB = get_fetu_binary_message(hka_deckB)
print("Fetu Hex/Binary Signatures: ")
print(hexsig_hexB, hexsigintB, bin_msgB)
print("\n")
